# Copyright (C) 2011-2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/dogo/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/dogo/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/sony/dogo/proprietary/bin/chargemon:system/bin/chargemon \
    vendor/sony/dogo/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/sony/dogo/proprietary/bin/e2fsck:system/bin/e2fsck \
    vendor/sony/dogo/proprietary/bin/efsks:system/bin/efsks \
    vendor/sony/dogo/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/sony/dogo/proprietary/bin/fmconfig:system/bin/fmconfig \
    vendor/sony/dogo/proprietary/bin/gsiff_daemon:system/bin/gsiff_daemon \
    vendor/sony/dogo/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/sony/dogo/proprietary/bin/illumination_service:system/bin/illumination_service \
    vendor/sony/dogo/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/sony/dogo/proprietary/bin/ks:system/bin/ks \
    vendor/sony/dogo/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/sony/dogo/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/sony/dogo/proprietary/bin/qcks:system/bin/qcks \
    vendor/sony/dogo/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/sony/dogo/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/sony/dogo/proprietary/bin/rild:system/bin/rild \
    vendor/sony/dogo/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/sony/dogo/proprietary/bin/system_monitor:system/bin/system_monitor \
    vendor/sony/dogo/proprietary/bin/ta_param_loader:system/bin/ta_param_loader \
    vendor/sony/dogo/proprietary/bin/ta_qmi_client:system/bin/ta_qmi_client \
    vendor/sony/dogo/proprietary/bin/taimport:system/bin/taimport \
    vendor/sony/dogo/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/sony/dogo/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/dogo/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/sony/dogo/proprietary/bin/usbhub_init:system/bin/usbhub_init

PRODUCT_COPY_FILES += \
    vendor/sony/dogo/proprietary/etc/firmware/cyttsp_8064_mtp.hex:system/etc/firmware/cyttsp_8064_mtp.hex \
    vendor/sony/dogo/proprietary/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex \
    vendor/sony/dogo/proprietary/etc/firmware/acdb.mbn:system/etc/firmware/acdb.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/apps.mbn:system/etc/firmware/apps.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/dsp1.mbn:system/etc/firmware/dsp1.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/dsp2.mbn:system/etc/firmware/dsp2.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/dsp3.mbn:system/etc/firmware/dsp3.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/dsps.b00:system/etc/firmware/dsps.b00 \
    vendor/sony/dogo/proprietary/etc/firmware/dsps.b01:system/etc/firmware/dsps.b01 \
    vendor/sony/dogo/proprietary/etc/firmware/dsps.b02:system/etc/firmware/dsps.b02 \
    vendor/sony/dogo/proprietary/etc/firmware/dsps.b03:system/etc/firmware/dsps.b03 \
    vendor/sony/dogo/proprietary/etc/firmware/dsps.b04:system/etc/firmware/dsps.b04 \
    vendor/sony/dogo/proprietary/etc/firmware/dsps.b05:system/etc/firmware/dsps.b05 \
    vendor/sony/dogo/proprietary/etc/firmware/dsps.mdt:system/etc/firmware/dsps.mdt \
    vendor/sony/dogo/proprietary/etc/firmware/dxhdcp2.b00:system/etc/firmware/dxhdcp2.b00 \
    vendor/sony/dogo/proprietary/etc/firmware/dxhdcp2.b01:system/etc/firmware/dxhdcp2.b01 \
    vendor/sony/dogo/proprietary/etc/firmware/dxhdcp2.b02:system/etc/firmware/dxhdcp2.b02 \
    vendor/sony/dogo/proprietary/etc/firmware/dxhdcp2.b03:system/etc/firmware/dxhdcp2.b03 \
    vendor/sony/dogo/proprietary/etc/firmware/dxhdcp2.mdt:system/etc/firmware/dxhdcp2.mdt \
    vendor/sony/dogo/proprietary/etc/firmware/efs1.mbn:system/etc/firmware/efs1.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/efs2.mbn:system/etc/firmware/efs2.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/efs3.mbn:system/etc/firmware/efs3.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/mdm_acdb.img:system/etc/firmware/mdm_acdb.img \
    vendor/sony/dogo/proprietary/etc/firmware/q6.b00:system/etc/firmware/q6.b00 \
    vendor/sony/dogo/proprietary/etc/firmware/q6.b01:system/etc/firmware/q6.b01 \
    vendor/sony/dogo/proprietary/etc/firmware/q6.b03:system/etc/firmware/q6.b03 \
    vendor/sony/dogo/proprietary/etc/firmware/q6.b04:system/etc/firmware/q6.b04 \
    vendor/sony/dogo/proprietary/etc/firmware/q6.b05:system/etc/firmware/q6.b05 \
    vendor/sony/dogo/proprietary/etc/firmware/q6.b06:system/etc/firmware/q6.b06 \
    vendor/sony/dogo/proprietary/etc/firmware/q6.mdt:system/etc/firmware/q6.mdt \
    vendor/sony/dogo/proprietary/etc/firmware/rpm.mbn:system/etc/firmware/rpm.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/sbl1.mbn:system/etc/firmware/sbl1.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/sbl2.mbn:system/etc/firmware/sbl2.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/ta.mbn:system/etc/firmware/ta.mbn \
    vendor/sony/dogo/proprietary/etc/firmware/touch_module_id_0x3c.img:system/etc/firmware/touch_module_id_0x3c.img \
    vendor/sony/dogo/proprietary/etc/firmware/touch_module_id_0x3d.img:system/etc/firmware/touch_module_id_0x3d.img \
    vendor/sony/dogo/proprietary/etc/firmware/touch_module_id_0x3f.img:system/etc/firmware/touch_module_id_0x3f.img \
    vendor/sony/dogo/proprietary/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/sony/dogo/proprietary/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/sony/dogo/proprietary/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/sony/dogo/proprietary/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/sony/dogo/proprietary/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/sony/dogo/proprietary/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/sony/dogo/proprietary/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/sony/dogo/proprietary/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/sony/dogo/proprietary/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/sony/dogo/proprietary/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/sony/dogo/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/sony/dogo/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/sony/dogo/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/sony/dogo/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/sony/dogo/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/sony/dogo/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/sony/dogo/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/sony/dogo/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
    vendor/sony/dogo/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
    vendor/sony/dogo/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
    vendor/sony/dogo/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
    vendor/sony/dogo/proprietary/etc/firmware/wcnss.b05:system/etc/firmware/wcnss.b05 \
    vendor/sony/dogo/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt

PRODUCT_COPY_FILES += \
    vendor/sony/dogo/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    vendor/sony/dogo/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini \
    vendor/sony/dogo/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin

PRODUCT_COPY_FILES += \
    vendor/sony/dogo/proprietary/etc/flashled_calc_parameters.cfg:system/etc/flashled_calc_parameters.cfg \
    vendor/sony/dogo/proprietary/lib/hw/audio.primary.msm8960.so:system/lib/hw/audio.primary.msm8960.so \
    vendor/sony/dogo/proprietary/lib/hw/audio_policy.msm8960.so:system/lib/hw/audio_policy.msm8960.so \
    vendor/sony/dogo/proprietary/lib/hw/bluetooth.default.so:system/lib/hw/bluetooth.default.so \
    vendor/sony/dogo/proprietary/lib/hw/camera.qcom.so:system/lib/hw/camera.vendor.qcom.so \
    vendor/sony/dogo/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/sony/dogo/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.vendor.default.so \
    vendor/sony/dogo/proprietary/lib/hw/nfc.msm8960.so:system/lib/hw/nfc.msm8960.so \
    vendor/sony/dogo/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/sony/dogo/proprietary/lib/libMiscTaAccessor.so:system/lib/libMiscTaAccessor.so \
    vendor/sony/dogo/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/sony/dogo/proprietary/lib/lib_asb_tee.so:system/lib/lib_asb_tee.so \
    vendor/sony/dogo/proprietary/lib/lib_get_secure_mode.so:system/lib/lib_get_secure_mode.so \
    vendor/sony/dogo/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/sony/dogo/proprietary/lib/libadsprpc.so:system/lib/libadsprpc.so \
    vendor/sony/dogo/proprietary/lib/libals.so:system/lib/libals.so \
    vendor/sony/dogo/proprietary/lib/libalsa-intf.so:system/lib/libalsa-intf.so \
    vendor/sony/dogo/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/sony/dogo/proprietary/lib/libbt-hci.so:system/lib/libbt-hci.so \
    vendor/sony/dogo/proprietary/lib/libbt-utils.so:system/lib/libbt-utils.so \
    vendor/sony/dogo/proprietary/lib/libcald_client.so:system/lib/libcald_client.so \
    vendor/sony/dogo/proprietary/lib/libcald_hal.so:system/lib/libcald_hal.so \
    vendor/sony/dogo/proprietary/lib/libcald_imageutil.so:system/lib/libcald_imageutil.so \
    vendor/sony/dogo/proprietary/lib/libcald_pal.so:system/lib/libcald_pal.so \
    vendor/sony/dogo/proprietary/lib/libcald_server.so:system/lib/libcald_server.so \
    vendor/sony/dogo/proprietary/lib/libcald_util.so:system/lib/libcald_util.so \
    vendor/sony/dogo/proprietary/lib/libcamera_clientsemc.so:system/lib/libcamera_clientsemc.so \
    vendor/sony/dogo/proprietary/lib/libcameralight.so:system/lib/libcameralight.so \
    vendor/sony/dogo/proprietary/lib/libcredential-manager-service.so:system/lib/libcredential-manager-service.so \
    vendor/sony/dogo/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/sony/dogo/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/sony/dogo/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/sony/dogo/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/sony/dogo/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/sony/dogo/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/sony/dogo/proprietary/lib/libface.so:system/lib/libface.so \
    vendor/sony/dogo/proprietary/lib/libfmradio.so:system/lib/libfmradio.so \
    vendor/sony/dogo/proprietary/lib/libfmradio.sony-iris.so:system/lib/libfmradio.sony-iris.so \
    vendor/sony/dogo/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/sony/dogo/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/sony/dogo/proprietary/lib/libidd.so:system/lib/libidd.so \
    vendor/sony/dogo/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/sony/dogo/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/sony/dogo/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/sony/dogo/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/sony/dogo/proprietary/lib/libkeyctrl.so:system/lib/libkeyctrl.so \
    vendor/sony/dogo/proprietary/lib/liblights-core.so:system/lib/liblights-core.so \
    vendor/sony/dogo/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/sony/dogo/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/sony/dogo/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/sony/dogo/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/sony/dogo/proprietary/lib/libmercury.so:system/lib/libmercury.so \
    vendor/sony/dogo/proprietary/lib/libmiscta.so:system/lib/libmiscta.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_3a_legacy.so:system/lib/libmmcamera_3a_legacy.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_imx091.so:system/lib/libmmcamera_imx091.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_tintless_algo.so:system/lib/libmmcamera_tintless_algo.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_tintless_wrapper.so:system/lib/libmmcamera_tintless_wrapper.so \
    vendor/sony/dogo/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/sony/dogo/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/sony/dogo/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/sony/dogo/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/sony/dogo/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/sony/dogo/proprietary/lib/libpin-cache.so:system/lib/libpin-cache.so \
    vendor/sony/dogo/proprietary/lib/libprotobuf-c.so:system/lib/libprotobuf-c.so \
    vendor/sony/dogo/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/sony/dogo/proprietary/lib/libqcci_adc.so:system/lib/libqcci_adc.so \
    vendor/sony/dogo/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/sony/dogo/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/sony/dogo/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/sony/dogo/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/sony/dogo/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/sony/dogo/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/sony/dogo/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/sony/dogo/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/sony/dogo/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/sony/dogo/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/sony/dogo/proprietary/lib/libsys-utils.so:system/lib/libsys-utils.so \
    vendor/sony/dogo/proprietary/lib/libsurround_proc.so:system/lib/libsurround_proc.so \
    vendor/sony/dogo/proprietary/lib/libsysmon.so:system/lib/libsysmon.so \
    vendor/sony/dogo/proprietary/lib/libsysmon_idd.so:system/lib/libsysmon_idd.so \
    vendor/sony/dogo/proprietary/lib/libsysmon_jni.so:system/lib/libsysmon_jni.so \
    vendor/sony/dogo/proprietary/lib/libta.so:system/lib/libta.so \
    vendor/sony/dogo/proprietary/lib/libthermalclient.so:system/lib/libthermalclient.so \
    vendor/sony/dogo/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    vendor/sony/dogo/proprietary/lib/libtime_genoff.so:obj/lib/libtime_genoff.so

PRODUCT_COPY_FILES += \
    vendor/sony/dogo/proprietary/vendor/lib/hw/power.qcom.so:system/vendor/lib/hw/power.qcom.so \
    vendor/sony/dogo/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/sony/dogo/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/sony/dogo/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/sony/dogo/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/sony/dogo/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/sony/dogo/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/sony/dogo/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/sony/dogo/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/sony/dogo/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/sony/dogo/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/sony/dogo/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/sony/dogo/proprietary/vendor/lib/libquipc_ulp_adapter.so:system/vendor/lib/libquipc_ulp_adapter.so \
    vendor/sony/dogo/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so

PRODUCT_COPY_FILES += \
    vendor/sony/dogo/proprietary/vendor/camera/APT00YP1.dat:system/vendor/camera/APT00YP1.dat \
    vendor/sony/dogo/proprietary/vendor/camera/flash.dat:system/vendor/camera/flash.dat \
    vendor/sony/dogo/proprietary/vendor/camera/KMO08BN0_IMX111.dat:system/vendor/camera/KMO08BN0_IMX111.dat \
    vendor/sony/dogo/proprietary/vendor/camera/LGI02BN0_IMX132.dat:system/vendor/camera/LGI02BN0_IMX132.dat \
    vendor/sony/dogo/proprietary/vendor/camera/LGI08BN2_DW9714.dat:system/vendor/camera/LGI08BN2_DW9714.dat \
    vendor/sony/dogo/proprietary/vendor/camera/LGI08BN2_IMX111.dat:system/vendor/camera/LGI08BN2_IMX111.dat \
    vendor/sony/dogo/proprietary/vendor/camera/product.dat:system/vendor/camera/product.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SEM02BN0_IMX132.dat:system/vendor/camera/SEM02BN0_IMX132.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SEM13BS0.dat:system/vendor/camera/SEM13BS0.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SEM13BS0_IMX135.dat:system/vendor/camera/SEM13BS0_IMX135.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SEM13BS0_WV570.dat:system/vendor/camera/SEM13BS0_WV570.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SEM13BS1.dat:system/vendor/camera/SEM13BS1.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SEM13BS1_IMX135.dat:system/vendor/camera/SEM13BS1_IMX135.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SEM13BS1_WV570.dat:system/vendor/camera/SEM13BS1_WV570.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SOI08BN1_IMX111.dat:system/vendor/camera/SOI08BN1_IMX111.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SOI13BS1.dat:system/vendor/camera/SOI13BS1.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SOI13BS1_DW9735.dat:system/vendor/camera/SOI13BS1_DW9735.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SOI13BS1_IMX135.dat:system/vendor/camera/SOI13BS1_IMX135.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SOI13BS2.dat:system/vendor/camera/SOI13BS2.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SOI13BS2_DW9735.dat:system/vendor/camera/SOI13BS2_DW9735.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SOI13BS2_IMX135.dat:system/vendor/camera/SOI13BS2_IMX135.dat \
    vendor/sony/dogo/proprietary/vendor/camera/SOI13BS9.dat:system/vendor/camera/SOI13BS9.dat \
    vendor/sony/dogo/proprietary/vendor/camera/STW00YP1.dat:system/vendor/camera/STW00YP1.dat

PRODUCT_COPY_FILES += \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_batt_therm.so:system/lib/sysmon/sysmon_batt_therm.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_bl_therm.so:system/lib/sysmon/sysmon_bl_therm.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_charge_current_limit_level.so:system/lib/sysmon/sysmon_charge_current_limit_level.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_corelimit.sosystem/lib/sysmon/sysmon_corelimit.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_disable_charging1.so:system/lib/sysmon/sysmon_disable_charging1.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_disable_charging2.so:system/lib/sysmon/sysmon_disable_charging2.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_enable_charging.so:system/lib/sysmon/sysmon_enable_charging.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_gpu_perflevel.so:system/lib/sysmon/sysmon_gpu_perflevel.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_lcd_brightness_level.so:system/lib/sysmon/sysmon_lcd_brightness_level.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_modem_lagan.so:system/lib/sysmon/sysmon_modem_lagan.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_pa_therm.so:system/lib/sysmon/sysmon_pa_therm.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_pba_therm.so:system/lib/sysmon/sysmon_pba_therm.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_perflevel.so:system/lib/sysmon/sysmon_perflevel.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_pm8921_tz.so:system/lib/sysmon/sysmon_pm8921_tz.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_test_sensor.so:system/lib/sysmon/sysmon_test_sensor.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor0.so:system/lib/sysmon/sysmon_tsens_tz_sensor0.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor1.so:system/lib/sysmon/sysmon_tsens_tz_sensor1.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor2.so:system/lib/sysmon/sysmon_tsens_tz_sensor2.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor3.so:system/lib/sysmon/sysmon_tsens_tz_sensor3.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor4.so:system/lib/sysmon/sysmon_tsens_tz_sensor4.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor5.so:system/lib/sysmon/sysmon_tsens_tz_sensor5.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor6.so:system/lib/sysmon/sysmon_tsens_tz_sensor6.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor7.so:system/lib/sysmon/sysmon_tsens_tz_sensor7.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor8.so:system/lib/sysmon/sysmon_tsens_tz_sensor8.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor9.so:system/lib/sysmon/sysmon_tsens_tz_sensor9.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_tsens_tz_sensor10.so:system/lib/sysmon/sysmon_tsens_tz_sensor10.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_usb_current_limit_level.so:system/lib/sysmon/sysmon_usb_current_limit_level.so \
    vendor/sony/dogo/proprietary/lib/sysmon/sysmon_wlan_limit.so:system/lib/sysmon/sysmon_wlan_limit.so

