# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES :=

# All the blobs
PRODUCT_COPY_FILES += \
vendor/sony/seagull/proprietary/bin/led_daemon:system/bin/led_daemon \
vendor/sony/seagull/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
vendor/sony/seagull/proprietary/bin/thermal-engine:system/bin/thermal-engine \
vendor/sony/seagull/proprietary/bin/adsprpcd:system/bin/adsprpcd \
vendor/sony/seagull/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
vendor/sony/seagull/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
vendor/sony/seagull/proprietary/bin/fmconfig:system/bin/fmconfig \
vendor/sony/seagull/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
vendor/sony/seagull/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
vendor/sony/seagull/proprietary/bin/netmgrd:system/bin/netmgrd \
vendor/sony/seagull/proprietary/bin/port-bridge:system/bin/port-bridge \
vendor/sony/seagull/proprietary/bin/qmiproxy:system/bin/qmiproxy \
vendor/sony/seagull/proprietary/bin/qmuxd:system/bin/qmuxd \
vendor/sony/seagull/proprietary/bin/radish:system/bin/radish \
vendor/sony/seagull/proprietary/bin/rild:system/bin/rild \
vendor/sony/seagull/proprietary/bin/rmt_storage:system/bin/rmt_storage \
vendor/sony/seagull/proprietary/bin/time_daemon:system/bin/time_daemon \
vendor/sony/seagull/proprietary/bin/btnvtool:system/bin/btnvtool \
vendor/sony/seagull/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
vendor/sony/seagull/proprietary/bin/gsiff_daemon:system/bin/gsiff_daemon \
vendor/sony/seagull/proprietary/bin/hvdcp:system/bin/hvdcp \
vendor/sony/seagull/proprietary/bin/irsc_util:system/bin/irsc_util \
vendor/sony/seagull/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
vendor/sony/seagull/proprietary/bin/mpdecision:system/bin/mpdecision \
vendor/sony/seagull/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
vendor/sony/seagull/proprietary/bin/qcom-system-daemon:system/bin/qcom-system-daemon \
vendor/sony/seagull/proprietary/bin/qseecomd:system/bin/qseecomd \
vendor/sony/seagull/proprietary/bin/rfs_access:system/bin/rfs_access \
vendor/sony/seagull/proprietary/bin/credmgrd:system/bin/credmgrd \
vendor/sony/seagull/proprietary/bin/scd:system/bin/scd \
vendor/sony/seagull/proprietary/bin/scdnotifier:system/bin/scdnotifier \
vendor/sony/seagull/proprietary/bin/sct_service:system/bin/sct_service \
vendor/sony/seagull/proprietary/bin/suntrold:system/bin/suntrold \
vendor/sony/seagull/proprietary/bin/taimport:system/bin/taimport \
vendor/sony/seagull/proprietary/bin/ta_qmi_service:system/bin/ta_qmi_service \
vendor/sony/seagull/proprietary/bin/updatemiscta:system/bin/updatemiscta \
vendor/sony/seagull/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
vendor/sony/seagull/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b00:system/etc/firmware/adsp.b00 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b01:system/etc/firmware/adsp.b01 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b02:system/etc/firmware/adsp.b02 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b03:system/etc/firmware/adsp.b03 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b04:system/etc/firmware/adsp.b04 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b05:system/etc/firmware/adsp.b05 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b06:system/etc/firmware/adsp.b06 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b07:system/etc/firmware/adsp.b07 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b08:system/etc/firmware/adsp.b08 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b09:system/etc/firmware/adsp.b09 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b10:system/etc/firmware/adsp.b10 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b11:system/etc/firmware/adsp.b11 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.b12:system/etc/firmware/adsp.b12 \
#vendor/sony/seagull/proprietary/etc/firmware/adsp.mdt:system/etc/firmware/adsp.mdt \
#vendor/sony/seagull/proprietary/etc/firmware/isdbtmm.b00:system/etc/firmware/isdbtmm.b00 \
#vendor/sony/seagull/proprietary/etc/firmware/isdbtmm.b01:system/etc/firmware/isdbtmm.b01 \
#vendor/sony/seagull/proprietary/etc/firmware/isdbtmm.b02:system/etc/firmware/isdbtmm.b02 \
#vendor/sony/seagull/proprietary/etc/firmware/isdbtmm.b03:system/etc/firmware/isdbtmm.b03 \
#vendor/sony/seagull/proprietary/etc/firmware/isdbtmm.mdt:system/etc/firmware/isdbtmm.mdt \
#vendor/sony/seagull/proprietary/etc/firmware/playready.b00:system/etc/firmware/playready.b00 \
#vendor/sony/seagull/proprietary/etc/firmware/playready.b01:system/etc/firmware/playready.b01 \
#vendor/sony/seagull/proprietary/etc/firmware/playready.b02:system/etc/firmware/playready.b02 \
#vendor/sony/seagull/proprietary/etc/firmware/playready.b03:system/etc/firmware/playready.b03 \
#vendor/sony/seagull/proprietary/etc/firmware/playready.mdt:system/etc/firmware/playready.mdt \
#vendor/sony/seagull/proprietary/etc/firmware/mc_v2.b00:system/etc/firmware/mc_v2.b00 \
#vendor/sony/seagull/proprietary/etc/firmware/mc_v2.b01:system/etc/firmware/mc_v2.b01 \
#vendor/sony/seagull/proprietary/etc/firmware/mc_v2.b02:system/etc/firmware/mc_v2.b02 \
#vendor/sony/seagull/proprietary/etc/firmware/mc_v2.b03:system/etc/firmware/mc_v2.b03 \
#vendor/sony/seagull/proprietary/etc/firmware/mc_v2.mdt:system/etc/firmware/mc_v2.mdt \

PRODUCT_COPY_FILES += \
vendor/sony/seagull/proprietary/etc/firmware/cmnlib.b00:system/etc/firmware/widevine.b00 \
vendor/sony/seagull/proprietary/etc/firmware/cmnlib.b01:system/etc/firmware/widevine.b01 \
vendor/sony/seagull/proprietary/etc/firmware/cmnlib.b02:system/etc/firmware/widevine.b02 \
vendor/sony/seagull/proprietary/etc/firmware/cmnlib.b03:system/etc/firmware/widevine.b03 \
vendor/sony/seagull/proprietary/etc/firmware/cmnlib.mdt:system/etc/firmware/widevine.mdt \
vendor/sony/seagull/proprietary/etc/firmware/cmnlib.b00:system/etc/firmware/cmnlib.b00 \
vendor/sony/seagull/proprietary/etc/firmware/cmnlib.b01:system/etc/firmware/cmnlib.b01 \
vendor/sony/seagull/proprietary/etc/firmware/cmnlib.b02:system/etc/firmware/cmnlib.b02 \
vendor/sony/seagull/proprietary/etc/firmware/cmnlib.b03:system/etc/firmware/cmnlib.b03 \
vendor/sony/seagull/proprietary/etc/firmware/cmnlib.mdt:system/etc/firmware/cmnlib.mdt \
#vendor/sony/seagull/proprietary/etc/firmware/mba.b00:system/etc/firmware/mba.b00 \
#vendor/sony/seagull/proprietary/etc/firmware/mba.mdt:system/etc/firmware/mba.mdt \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b05:system/etc/firmware/modem.b05 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b10:system/etc/firmware/modem.b10 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b14:system/etc/firmware/modem.b14 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b20:system/etc/firmware/modem.b20 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b21:system/etc/firmware/modem.b21 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b26:system/etc/firmware/modem.b26 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.b27:system/etc/firmware/modem.b27 \
#vendor/sony/seagull/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \

PRODUCT_COPY_FILES += \
vendor/sony/seagull/proprietary/etc/firmware/tzhdcp.b00:system/etc/firmware/tzhdcp.b00 \
vendor/sony/seagull/proprietary/etc/firmware/tzhdcp.b01:system/etc/firmware/tzhdcp.b01 \
vendor/sony/seagull/proprietary/etc/firmware/tzhdcp.b02:system/etc/firmware/tzhdcp.b02 \
vendor/sony/seagull/proprietary/etc/firmware/tzhdcp.b03:system/etc/firmware/tzhdcp.b03 \
vendor/sony/seagull/proprietary/etc/firmware/tzhdcp.mdt:system/etc/firmware/tzhdcp.mdt \
vendor/sony/seagull/proprietary/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
vendor/sony/seagull/proprietary/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
vendor/sony/seagull/proprietary/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
vendor/sony/seagull/proprietary/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
vendor/sony/seagull/proprietary/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
vendor/sony/seagull/proprietary/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
vendor/sony/seagull/proprietary/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
vendor/sony/seagull/proprietary/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
vendor/sony/seagull/proprietary/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
vendor/sony/seagull/proprietary/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
vendor/sony/seagull/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
vendor/sony/seagull/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
vendor/sony/seagull/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
vendor/sony/seagull/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
vendor/sony/seagull/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
vendor/sony/seagull/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
#vendor/sony/seagull/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
#vendor/sony/seagull/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
#vendor/sony/seagull/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
#vendor/sony/seagull/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
#vendor/sony/seagull/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
#vendor/sony/seagull/proprietary/etc/firmware/wcnss.b06:system/etc/firmware/wcnss.b06 \
#vendor/sony/seagull/proprietary/etc/firmware/wcnss.b07:system/etc/firmware/wcnss.b07 \
#vendor/sony/seagull/proprietary/etc/firmware/wcnss.b08:system/etc/firmware/wcnss.b08 \
#vendor/sony/seagull/proprietary/etc/firmware/wcnss.b09:system/etc/firmware/wcnss.b09 \
#vendor/sony/seagull/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt \

PRODUCT_COPY_FILES += \
vendor/sony/seagull/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
vendor/sony/seagull/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
vendor/sony/seagull/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
vendor/sony/seagull/proprietary/lib/lib_asb_tee.so:system/lib/lib_asb_tee.so \
vendor/sony/seagull/proprietary/lib/libMiscTaAccessor.so:system/lib/libMiscTaAccessor.so \
vendor/sony/seagull/proprietary/lib/libcamera_clientsemc.so:system/lib/libcamera_clientsemc.so \
vendor/sony/seagull/proprietary/lib/libchromatix_imx135_liveshot.so:system/lib/libchromatix_imx135_liveshot.so \
vendor/sony/seagull/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
vendor/sony/seagull/proprietary/lib/libkeyctrl.so:system/lib/libkeyctrl.so \
vendor/sony/seagull/proprietary/lib/liblights-core.so:system/lib/liblights-core.so \
vendor/sony/seagull/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
vendor/sony/seagull/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
vendor/sony/seagull/proprietary/lib/libmiscta.so:system/lib/libmiscta.so \
vendor/sony/seagull/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
vendor/sony/seagull/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
vendor/sony/seagull/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
vendor/sony/seagull/proprietary/lib/libmorpho_denoiser.so:system/lib/libmorpho_denoiser.so \
vendor/sony/seagull/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
vendor/sony/seagull/proprietary/lib/libmorpho_edit_engine.so:system/lib/libmorpho_edit_engine.so \
vendor/sony/seagull/proprietary/lib/libmorpho_fdw.so:system/lib/libmorpho_fdw.so \
vendor/sony/seagull/proprietary/lib/libmorpho_hdr_checker.so:system/lib/libmorpho_hdr_checker.so \
vendor/sony/seagull/proprietary/lib/libmorpho_image_stabilizer3.so:system/lib/libmorpho_image_stabilizer3.so \
vendor/sony/seagull/proprietary/lib/libmorpho_movie_stabilizer3.so:system/lib/libmorpho_movie_stabilizer3.so \
vendor/sony/seagull/proprietary/lib/libmorpho_object_tracker2.so:system/lib/libmorpho_object_tracker2.so \
vendor/sony/seagull/proprietary/lib/libmorpho_posture_detect.so:system/lib/libmorpho_posture_detect.so \
vendor/sony/seagull/proprietary/lib/libmorpho_scene_detector.so:system/lib/libmorpho_scene_detector.so \
vendor/sony/seagull/proprietary/lib/libmorpho_super_resolution.so:system/lib/libmorpho_super_resolution.so \
vendor/sony/seagull/proprietary/lib/libnfc-nci.so:system/lib/libnfc-nci.so \
vendor/sony/seagull/proprietary/lib/libpin-cache.so:system/lib/libpin-cache.so \
vendor/sony/seagull/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
vendor/sony/seagull/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
vendor/sony/seagull/proprietary/lib/libril.so:system/lib/libril.so \
vendor/sony/seagull/proprietary/lib/librilutils.so:system/lib/librilutils.so \
vendor/sony/seagull/proprietary/lib/libsys-utils.so:system/lib/libsys-utils.so \
vendor/sony/seagull/proprietary/lib/libta.so:system/lib/libta.so \
vendor/sony/seagull/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
vendor/sony/seagull/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
vendor/sony/seagull/proprietary/lib/hw/camera.msm8226.so:system/lib/hw/camera.vendor.msm8226.so \
vendor/sony/seagull/proprietary/lib/hw/lights.msm8226.so:system/lib/hw/lights.vendor.msm8226.so \
vendor/sony/seagull/proprietary/lib/hw/nfc_nci_pn547.default.so:system/lib/hw/nfc_nci_pn547.default.so \
vendor/sony/seagull/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
vendor/sony/seagull/proprietary/lib/soundfx/libposteffectwrapper.so:system/lib/soundfx/libposteffectwrapper.so \
vendor/sony/seagull/proprietary/lib/soundfx/libpreeffectwrapper.so:system/lib/soundfx/libpreeffectwrapper.so \
vendor/sony/seagull/proprietary/lib/soundfx/libqcompostprocbundle.so:system/lib/soundfx/libqcompostprocbundle.so \
vendor/sony/seagull/proprietary/lib/soundfx/libqcomvisualizer.so:system/lib/soundfx/libqcomvisualizer.so \
vendor/sony/seagull/proprietary/lib/soundfx/libqcomvoiceprocessing.so:system/lib/soundfx/libqcomvoiceprocessing.so \
vendor/sony/seagull/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
vendor/sony/seagull/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
vendor/sony/seagull/proprietary/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
vendor/sony/seagull/proprietary/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
vendor/sony/seagull/proprietary/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
vendor/sony/seagull/proprietary/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
vendor/sony/seagull/proprietary/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
vendor/sony/seagull/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
vendor/sony/seagull/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
vendor/sony/seagull/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
vendor/sony/seagull/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
vendor/sony/seagull/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
vendor/sony/seagull/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
vendor/sony/seagull/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
vendor/sony/seagull/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
vendor/sony/seagull/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
vendor/sony/seagull/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_common_2nd.so:system/vendor/lib/libchromatix_imx134_common_2nd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_common_lsc.so:system/vendor/lib/libchromatix_imx134_common_lsc.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_default_video_2nd.so:system/vendor/lib/libchromatix_imx134_default_video_2nd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_default_video_lsc.so:system/vendor/lib/libchromatix_imx134_default_video_lsc.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_preview_2nd.so:system/vendor/lib/libchromatix_imx134_preview_2nd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_preview_lsc.so:system/vendor/lib/libchromatix_imx134_preview_lsc.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_snapshot_2nd.so:system/vendor/lib/libchromatix_imx134_snapshot_2nd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_snapshot_lsc.so:system/vendor/lib/libchromatix_imx134_snapshot_lsc.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_video_hdr.so:system/vendor/lib/libchromatix_imx134_video_hdr.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_video_hdr_2nd.so:system/vendor/lib/libchromatix_imx134_video_hdr_2nd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx134_video_hdr_lsc.so:system/vendor/lib/libchromatix_imx134_video_hdr_lsc.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx135_hfr_60.so:system/vendor/lib/libchromatix_imx135_hfr_60.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx135_hfr_90.so:system/vendor/lib/libchromatix_imx135_hfr_90.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx188_common.so:system/vendor/lib/libchromatix_imx188_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx188_common_2nd.so:system/vendor/lib/libchromatix_imx188_common_2nd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx188_default_video.so:system/vendor/lib/libchromatix_imx188_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx188_default_video_2nd.so:system/vendor/lib/libchromatix_imx188_default_video_2nd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx188_preview.so:system/vendor/lib/libchromatix_imx188_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx188_preview_2nd.so:system/vendor/lib/libchromatix_imx188_preview_2nd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx188_snapshot.so:system/vendor/lib/libchromatix_imx188_snapshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_imx188_snapshot_2nd.so:system/vendor/lib/libchromatix_imx188_snapshot_2nd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_s5k3l1yx_common.so:system/vendor/lib/libchromatix_s5k3l1yx_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_s5k3l1yx_liveshot.so:system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_s5k3l1yx_snapshot.so:system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
vendor/sony/seagull/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
vendor/sony/seagull/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
vendor/sony/seagull/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
vendor/sony/seagull/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
vendor/sony/seagull/proprietary/vendor/lib/libcneutils.so:system/vendor/lib/libcneutils.so \
vendor/sony/seagull/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
vendor/sony/seagull/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
vendor/sony/seagull/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
vendor/sony/seagull/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
vendor/sony/seagull/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
vendor/sony/seagull/proprietary/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
vendor/sony/seagull/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
vendor/sony/seagull/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
vendor/sony/seagull/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
vendor/sony/seagull/proprietary/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
vendor/sony/seagull/proprietary/vendor/lib/libdsucsd.so:system/vendor/lib/libdsucsd.so \
vendor/sony/seagull/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
vendor/sony/seagull/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
vendor/sony/seagull/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
vendor/sony/seagull/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
vendor/sony/seagull/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
vendor/sony/seagull/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
vendor/sony/seagull/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
vendor/sony/seagull/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
vendor/sony/seagull/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-imscamera.so:system/vendor/lib/lib-imscamera.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
vendor/sony/seagull/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
vendor/sony/seagull/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
vendor/sony/seagull/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
vendor/sony/seagull/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
vendor/sony/seagull/proprietary/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so \
vendor/sony/seagull/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
vendor/sony/seagull/proprietary/vendor/lib/liblisten.so:system/vendor/lib/liblisten.so \
vendor/sony/seagull/proprietary/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so \
vendor/sony/seagull/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
vendor/sony/seagull/proprietary/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
vendor/sony/seagull/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
vendor/sony/seagull/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
vendor/sony/seagull/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_imx134_Sony_eeprom.so:system/vendor/lib/libmmcamera_imx134_Sony_eeprom.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_imx188.so:system/vendor/lib/libmmcamera_imx188.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
vendor/sony/seagull/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
vendor/sony/seagull/proprietary/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmQTA.so:system/vendor/lib/libmmQTA.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so \
vendor/sony/seagull/proprietary/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so \
vendor/sony/seagull/proprietary/vendor/lib/libmsapm_jni.so:system/vendor/lib/libmsapm_jni.so \
vendor/sony/seagull/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
vendor/sony/seagull/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
vendor/sony/seagull/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
vendor/sony/seagull/proprietary/vendor/lib/liboi_sbc_decoder.so:system/vendor/lib/liboi_sbc_decoder.so \
vendor/sony/seagull/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
vendor/sony/seagull/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
vendor/sony/seagull/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
vendor/sony/seagull/proprietary/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
vendor/sony/seagull/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
vendor/sony/seagull/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
vendor/sony/seagull/proprietary/vendor/lib/libP11Notify.so:system/vendor/lib/libP11Notify.so \
vendor/sony/seagull/proprietary/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so \
vendor/sony/seagull/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
vendor/sony/seagull/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
vendor/sony/seagull/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
vendor/sony/seagull/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
vendor/sony/seagull/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
vendor/sony/seagull/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
vendor/sony/seagull/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
vendor/sony/seagull/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
vendor/sony/seagull/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
vendor/sony/seagull/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
vendor/sony/seagull/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
vendor/sony/seagull/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
vendor/sony/seagull/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
vendor/sony/seagull/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
vendor/sony/seagull/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
vendor/sony/seagull/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
vendor/sony/seagull/proprietary/vendor/lib/libquipc_ulp_adapter.so:system/vendor/lib/libquipc_ulp_adapter.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so \
vendor/sony/seagull/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
vendor/sony/seagull/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
vendor/sony/seagull/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
vendor/sony/seagull/proprietary/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
vendor/sony/seagull/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
vendor/sony/seagull/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
vendor/sony/seagull/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
vendor/sony/seagull/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
vendor/sony/seagull/proprietary/vendor/lib/libsrsprocessing.so:system/vendor/lib/libsrsprocessing.so \
vendor/sony/seagull/proprietary/vendor/lib/libSSEPKCS11.so:system/vendor/lib/libSSEPKCS11.so \
vendor/sony/seagull/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
vendor/sony/seagull/proprietary/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so \
vendor/sony/seagull/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
vendor/sony/seagull/proprietary/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
vendor/sony/seagull/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
vendor/sony/seagull/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
vendor/sony/seagull/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
vendor/sony/seagull/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
vendor/sony/seagull/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
vendor/sony/seagull/proprietary/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so \
vendor/sony/seagull/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
vendor/sony/seagull/proprietary/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
vendor/sony/seagull/proprietary/vendor/lib/libwifiscanner.so:system/vendor/lib/libwifiscanner.so \
vendor/sony/seagull/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
vendor/sony/seagull/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
vendor/sony/seagull/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
vendor/sony/seagull/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
vendor/sony/seagull/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
vendor/sony/seagull/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
vendor/sony/seagull/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
vendor/sony/seagull/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
vendor/sony/seagull/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
vendor/sony/seagull/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
vendor/sony/seagull/proprietary/vendor/lib/hw/power.qcom.so:system/vendor/lib/hw/power.qcom.so \
vendor/sony/seagull/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
vendor/sony/seagull/proprietary/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so:system/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so \
vendor/sony/seagull/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
vendor/sony/seagull/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
vendor/sony/seagull/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
vendor/sony/seagull/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
vendor/sony/seagull/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
vendor/sony/seagull/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
vendor/sony/seagull/proprietary/lib/libcnefeatureconfig.so:obj/lib/libcnefeatureconfig.so \
vendor/sony/seagull/proprietary/vendor/lib/libtime_genoff.so:obj/lib/libtime_genoff.so \
